name: Keep Render Alive

on:
  schedule:
    # Chạy mỗi 15 phút (24/7)
    - cron: '*/15 * * * *'
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://dr-smile-api-prod-kam4.onrender.com/api/health
 